apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mysql
  namespace: mysql
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - mysql
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: clusters/development-primary
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: mysql
  name: mysql-subscription-1
  namespace: mysql
spec:
  channel: ggithubcom-senthilredhat-acm-test01-ns/ggithubcom-senthilredhat-acm-test01
  placement:
    placementRef:
      kind: PlacementRule
      name: production-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: mysql
  name: production-placement
  namespace: mysql
spec:
  clusterSelector:
    matchLabels:
      env: production