apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: maintanance-group-2
  namespace:  maintanance-group-2
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          -  maintanance-group-2