apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: hello-world
  name: mysql-production-placement
  namespace: helloworld
spec:
  clusterSelector:
    matchLabels:
      env: production