apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: clusters/development-primary/hello-world
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: hello-world
  name: hello-world-subscription-1
  namespace: hello-world
spec:
  channel: ggithubcom-senthilredhat-acm-test01-ns/ggithubcom-senthilredhat-acm-test01
  placement:
    placementRef:
      kind: PlacementRule
      name: hello-world-production-placement