apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: hello-world
  name: hello-world
spec:
  to:
    kind: Service
    name: hello-world
    weight: 100
  wildcardPolicy: None

