apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: app-of-apps
  name: app-of-apps-subscription-1
  namespace: app-of-apps
spec:
  channel: git-do480-apps-ns/git-do480-apps
  placement:
    placementRef:
      kind: PlacementRule
      name: app-of-apps-placement