apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../groups/all
  - ../../groups/prod
  - ../../groups/geo-east

resources:
  - ./overlays/mysql


nameSuffix: -stage-primary