apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/maintanance-group-2
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: maintanance-group-2
  name:  maintanance-group-2-subscription
  namespace:  maintanance-group-2
spec:
  channel: ggithubcom-senthilredhat-acm-test01-ns/ggithubcom-senthilredhat-acm-test01
  placement:
    placementRef:
      kind: PlacementRule
      name: acm-cluster-placement